services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: biomagnetismo-dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app           # Sincroniza tu código en tiempo real
      - /app/node_modules # Evita que Docker intente sincronizar los paquetes locales
    environment:
      - CHOKIDAR_USEPOLLING=true # Refuerza la detección de cambios